X-Nav-Enhet header
navikt/syfosmmanuell-backend pull request #10
Opened 2020-10-19 07:03 UTC by sebdak

2020-10-19 07:13 UTC, tiafiring commented on src/main/kotlin/no/nav/syfo/oppgave/service/OppgaveService.kt
> +        tildeltEnhetsnr = tildeltEnhetsnr
Hvis du har veileders ident kan du gjerne sende med den også som "tilordnetRessurs" :)

2020-10-19 07:17 UTC, tiafiring approved these changes

2020-10-19 07:18 UTC, sebdak commented on src/main/kotlin/no/nav/syfo/oppgave/service/OppgaveService.kt
> +        tildeltEnhetsnr = tildeltEnhetsnr
tenkte å ta det i en separat pr, men kan forsåvidt gjøre det her?

2020-10-19 07:18 UTC, andreasDev commented on src/main/kotlin/no/nav/syfo/persistering/api/SendVurderingManuellOppgaveRest.kt
> +                oppgaveId == null -> {
denne oppgaveID vil aldri være null her, så denne sjekke kan fjernes. .toInt() vil kaste exception på linje 25 om det ikke er en int.  Da burde vi kanskje hatt en exceptionmapper i (StatusPages) som lager en BadRequest ved NumberFormatException

2020-10-19 07:20 UTC, andreasDev requested changes
Sjekk kommentar

2020-10-19 07:40 UTC, tiasg commented on src/main/kotlin/no/nav/syfo/persistering/api/SendVurderingManuellOppgaveRest.kt
> +                oppgaveId == null -> {
Hvis du bruker toIntOrNull() i stedet @sebdak så kan du sjekke det på den måten du allerede gjør :)

2020-10-19 07:44 UTC, sebdak commented on src/main/kotlin/no/nav/syfo/persistering/api/SendVurderingManuellOppgaveRest.kt
> +                oppgaveId == null -> {
@andreasDev hvis vi gjør denne mappingen, hva skal da settes som message? Vi vet vel ikke i mappingen om det var akkurat "oppgaveid" som kastet exception?

2020-10-19 08:07 UTC, tiasg commented on src/main/kotlin/no/nav/syfo/persistering/api/SendVurderingManuellOppgaveRest.kt
> +                oppgaveId == null -> {
@sebdak Som sagt, hvis du bare endrer det til toIntOrNull() så trenger du ikke gjøre noe mer :)

2020-10-19 08:17 UTC, andreasDev commented on src/main/kotlin/no/nav/syfo/persistering/api/SendVurderingManuellOppgaveRest.kt
> +                oppgaveId == null -> {
Ja den kan jo også brukes, bra tenkt! @tiasg

2020-10-19 09:11 UTC, tiafiring commented on src/main/kotlin/no/nav/syfo/oppgave/service/OppgaveService.kt
> +        tildeltEnhetsnr = tildeltEnhetsnr
neida, kan gjerne ta det i en egen :)

2020-10-19 12:29 UTC, tiafiring commented on src/main/kotlin/no/nav/syfo/persistering/api/SendVurderingManuellOppgaveRest.kt
> +                        // Not found
Disse kommentarene trengs kanskje ikke, eller? :)

2020-10-19 12:34 UTC, tiafiring commented on src/main/kotlin/no/nav/syfo/service/ManuellOppgaveService.kt
> +            if (!authorizationService.hasAccess(accessToken, pasientFnr)) {
Vi bør gjøre tilgangssjekk før vi sjekker om oppgaven finnes for å unngå å lekke informasjon :)

2020-10-19 12:36 UTC, tiafiring commented on src/main/kotlin/no/nav/syfo/service/ManuellOppgaveService.kt
> +            if (!authorizationService.hasAccess(accessToken, pasientFnr)) {
hmm, det blir kanskje vanskelig å få til i praksis siden vi må sjekke hvem oppgaven gjelder..

2020-10-19 12:37 UTC, tiafiring commented on src/main/kotlin/no/nav/syfo/service/ManuellOppgaveService.kt
>          val manuellOppgave = hentManuellOppgave(oppgaveId, accessToken)
Her må vi også sjekke at bruker faktisk har tilgang til å ferdigstille denne oppgaven

2020-10-19 12:38 UTC, tiafiring commented on src/main/kotlin/no/nav/syfo/service/ManuellOppgaveService.kt
>          val manuellOppgave = hentManuellOppgave(oppgaveId, accessToken)
Ah, det ble gjort lenger ned :)

2020-10-19 12:40 UTC, sebdak commented on src/main/kotlin/no/nav/syfo/persistering/api/SendVurderingManuellOppgaveRest.kt
> +                        // Not found
Nei, det gjør det ikke :P glemte å fjerne

2020-10-19 13:14 UTC, sebdak commented on src/main/kotlin/no/nav/syfo/persistering/api/SendVurderingManuellOppgaveRest.kt
> +                oppgaveId == null -> {
> @sebdak Som sagt, hvis du bare endrer det til toIntOrNull() så trenger du ikke gjøre noe mer :)

Fikk ikke kommentaren din før jeg postet min egen

2020-10-19 13:23 UTC, andreasDev commented on src/main/kotlin/no/nav/syfo/clients/HttpClients.kt
> +        .maximumSize(100)
Bare å øke size her egentlig, kan godt være 1000+

2020-10-19 13:48 UTC, andreasDev commented on src/main/kotlin/no/nav/syfo/persistering/api/SendVurderingManuellOppgaveRest.kt
> +                    log.error("Mangler X-Nav-Enhet i http header")
Her burde teksten byttes til "X-Nav-Enhet er ugyldig" da den ikke kan mangle her

2020-10-19 14:03 UTC, andreasDev commented on src/main/kotlin/no/nav/syfo/service/ManuellOppgaveService.kt
> +            if (!authorizationService.hasAccess(accessToken, pasientFnr)) {
Det er ofte lurt å gjøre tilgangskontroll så tidlig så mulig og ikke ha det nede i tjenestelaget. Dette kan skape problemer i fremtiden ved utvidelser og endring i koden. Vi burde ha det som det første i APIet, og det beste hadde egentlig vært å gjort det før selve logikken til APIet i AuthenticationPipeline.

2020-10-19 14:06 UTC, andreasDev commented on src/main/kotlin/no/nav/syfo/persistering/api/SendVurderingManuellOppgaveRest.kt
>                      call.respond(HttpStatusCode.BadRequest)
Trenger egentlig ikke sjekke accessToken her heller da dette sjekkes i authentication pipeline. Så burde vi respondere med Unauthorised og ikke BadRequest

2020-10-20 07:18 UTC, sebdak commented on src/main/kotlin/no/nav/syfo/persistering/api/SendVurderingManuellOppgaveRest.kt
> +                    log.error("Mangler X-Nav-Enhet i http header")
Er du sikker på at den ikke kan mangle? `call.request.headers["X-Nav-Enhet"]` kan returnere null?

2020-10-20 07:21 UTC, sebdak commented on src/main/kotlin/no/nav/syfo/persistering/api/SendVurderingManuellOppgaveRest.kt
>                      call.respond(HttpStatusCode.BadRequest)
slenge på en "!!" på accesstoken da?

2020-10-20 08:06 UTC, andreasDev commented on src/main/kotlin/no/nav/syfo/persistering/api/SendVurderingManuellOppgaveRest.kt
> +                    log.error("Mangler X-Nav-Enhet i http header")
åja, jeg tenkte på feil 👍

2020-10-20 08:06 UTC, andreasDev commented on src/main/kotlin/no/nav/syfo/persistering/api/SendVurderingManuellOppgaveRest.kt
> +                    log.error("Mangler X-Nav-Enhet i http header")
Jeg tenkte på oppgaveId (path param) som aldri kan være null

2020-10-20 08:08 UTC, andreasDev approved these changes

2020-10-20 08:08 UTC, andreasDev commented
Ser bra ut! bra jobba!

2020-10-20 09:16 UTC, tiafiring approved these changes

2020-10-22 16:49 UTC, merged